// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlympicGamesChristensen.Models;

#nullable disable

namespace OlympicGamesChristensen.Migrations
{
    [DbContext(typeof(CountryContext))]
    [Migration("20221013001644_newkey")]
    partial class newkey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OlympicGamesChristensen.Models.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = "in",
                            CategoryName = "Indoor Olympics"
                        },
                        new
                        {
                            CategoryID = "out",
                            CategoryName = "Outdoor Olympics"
                        });
                });

            modelBuilder.Entity("OlympicGamesChristensen.Models.Country", b =>
                {
                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.HasIndex("CategoryID");

                    b.HasIndex("GameID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = "swd",
                            CategoryID = "in",
                            CountryName = "Sweden",
                            FlagImage = "Sweden.png",
                            GameID = "win",
                            Sport = "Curling"
                        },
                        new
                        {
                            CountryId = "cnd",
                            CategoryID = "in",
                            CountryName = "Canada",
                            FlagImage = "Canada.png",
                            GameID = "win",
                            Sport = "Curling"
                        },
                        new
                        {
                            CountryId = "gbt",
                            CategoryID = "in",
                            CountryName = "Great Britain",
                            FlagImage = "GreatBritain.png",
                            GameID = "win",
                            Sport = "Curling"
                        },
                        new
                        {
                            CountryId = "jam",
                            CategoryID = "out",
                            CountryName = "Jamaica",
                            FlagImage = "Jamaica.png",
                            GameID = "win",
                            Sport = "Bobsleigh"
                        },
                        new
                        {
                            CountryId = "ity",
                            CategoryID = "out",
                            CountryName = "Italy",
                            FlagImage = "Italy.png",
                            GameID = "win",
                            Sport = "Bobsleigh"
                        },
                        new
                        {
                            CountryId = "jap",
                            CategoryID = "out",
                            CountryName = "Japan",
                            FlagImage = "Japan.png",
                            GameID = "win",
                            Sport = "Bobsleigh"
                        },
                        new
                        {
                            CountryId = "gem",
                            CategoryID = "in",
                            CountryName = "Germany",
                            FlagImage = "Germany.png",
                            GameID = "sum",
                            Sport = "Diving"
                        },
                        new
                        {
                            CountryId = "cin",
                            CategoryID = "in",
                            CountryName = "China",
                            FlagImage = "China.png",
                            GameID = "sum",
                            Sport = "Diving"
                        },
                        new
                        {
                            CountryId = "mex",
                            CategoryID = "in",
                            CountryName = "Mexico",
                            FlagImage = "Mexico.png",
                            GameID = "sum",
                            Sport = "Diving"
                        },
                        new
                        {
                            CountryId = "baz",
                            CategoryID = "out",
                            CountryName = "Brazil",
                            FlagImage = "Brazil.png",
                            GameID = "sum",
                            Sport = "Road Cycling"
                        },
                        new
                        {
                            CountryId = "net",
                            CategoryID = "out",
                            CountryName = "Netherlands",
                            FlagImage = "Netherlands.png",
                            GameID = "sum",
                            Sport = "Road Cycling"
                        },
                        new
                        {
                            CountryId = "usa",
                            CategoryID = "out",
                            CountryName = "USA",
                            FlagImage = "USA.png",
                            GameID = "sum",
                            Sport = "Road Cycling"
                        },
                        new
                        {
                            CountryId = "tai",
                            CategoryID = "in",
                            CountryName = "Thailand",
                            FlagImage = "Thailand.png",
                            GameID = "par",
                            Sport = "Archery"
                        },
                        new
                        {
                            CountryId = "urg",
                            CategoryID = "in",
                            CountryName = "Uruguay",
                            FlagImage = "Uruguay.png",
                            GameID = "par",
                            Sport = "Archery"
                        },
                        new
                        {
                            CountryId = "ukr",
                            CategoryID = "in",
                            CountryName = "Ukraine",
                            FlagImage = "Ukraine.png",
                            GameID = "par",
                            Sport = "Archery"
                        },
                        new
                        {
                            CountryId = "aus",
                            CategoryID = "out",
                            CountryName = "Austria",
                            FlagImage = "Austria.png",
                            GameID = "par",
                            Sport = "Canoe Sprint"
                        },
                        new
                        {
                            CountryId = "pak",
                            CategoryID = "out",
                            CountryName = "Pakistan",
                            FlagImage = "Pakistan.png",
                            GameID = "par",
                            Sport = "Canoe Sprint"
                        },
                        new
                        {
                            CountryId = "zim",
                            CategoryID = "out",
                            CountryName = "Zimbabwe",
                            FlagImage = "Zimbabwe.png",
                            GameID = "par",
                            Sport = "Canoe Sprint"
                        },
                        new
                        {
                            CountryId = "fan",
                            CategoryID = "in",
                            CountryName = "France",
                            FlagImage = "France.png",
                            GameID = "yth",
                            Sport = "Break Dancing"
                        },
                        new
                        {
                            CountryId = "cyp",
                            CategoryID = "in",
                            CountryName = "Cyprus",
                            FlagImage = "Cyprus.png",
                            GameID = "yth",
                            Sport = "Break Dancing"
                        },
                        new
                        {
                            CountryId = "rus",
                            CategoryID = "out",
                            CountryName = "Russia",
                            FlagImage = "Russia.png",
                            GameID = "yth",
                            Sport = "Break Dancing"
                        },
                        new
                        {
                            CountryId = "fin",
                            CategoryID = "out",
                            CountryName = "Finland",
                            FlagImage = "Finland.png",
                            GameID = "yth",
                            Sport = "Skateboarding"
                        },
                        new
                        {
                            CountryId = "slo",
                            CategoryID = "out",
                            CountryName = "Slovakia",
                            FlagImage = "Slovakia.png",
                            GameID = "yth",
                            Sport = "Skateboarding"
                        },
                        new
                        {
                            CountryId = "por",
                            CategoryID = "out",
                            CountryName = "Portugal",
                            FlagImage = "Portugal.png",
                            GameID = "yth",
                            Sport = "Skateboarding"
                        });
                });

            modelBuilder.Entity("OlympicGamesChristensen.Models.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = "win",
                            GameName = "Winter Olympics"
                        },
                        new
                        {
                            GameId = "sum",
                            GameName = "Summer Olympics"
                        },
                        new
                        {
                            GameId = "par",
                            GameName = "Paralympic Olympics"
                        },
                        new
                        {
                            GameId = "yth",
                            GameName = "Youth Olympics"
                        });
                });

            modelBuilder.Entity("OlympicGamesChristensen.Models.Country", b =>
                {
                    b.HasOne("OlympicGamesChristensen.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlympicGamesChristensen.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
